name: shenfun
channels:
  - conda-forge
dependencies:
  - shenfun
  - python=3.10.6
  - mpi4py
  - FFTW
  - mpi4py-fft
  - cython
  - numpy
  - sympy
  - scipy
  - h5py
  - pyyaml
  - mpich
  - h5py=*=mpi* 
  - netcdf4=*=mpi*
